### ISSUE TITLE
Please add the support to 'delimiter' parameter of storage.getFiles() method

### ISSUE THREAD

**Issue by vincenzodibiaggio** [DrPaulBrewer/zip-bucket#6]
`return (promiseRetry((retry)=>(storage.bucket(fromBucket).getFiles({prefix:fromPath}).catch(retry)), backoffStrategy)`

here https://github.com/DrPaulBrewer/zip-bucket/blob/24b4fac2da04155d4706323269de9509e4894ec5/index.js#L51

**Comment by vincenzodibiaggio** [comment]
use case:

a list of file that begins with a code and ends with a type like `111abc type.ext, 111abc typeB.ext, 111def typeB.ext`. I need to create a zipfile with all files with the code `111` and the type `typeB`

**Comment by DrPaulBrewer** [comment]
There is a another way to filter by file name or extension without changing the zip-bucket code.  Instead, pass a function to `mapper` parameter of `zipBucket(storage)({... mapper: function })` 

Look at [index.js line 58](https://github.com/DrPaulBrewer/zip-bucket/blob/master/index.js#L58) it shows `mapper` is called for each file `f`  found in bucket:

(`f` is object of file information from Google Storage API, `f.name` is file name within bucket)

`pathInZip= mapper( f, pathInZip) ;`  

where previous value of `pathInZip` is a default based on file name `f.name` and `fromPath` generated in `suggestedName()`

Line 59 shows if `mapper` returns `false` instead of a string then function will return without reading the file.  File should not be in zip archive if `mapper` returns `false` for that file.

For example, if you only want ".txt" files I would think something like

`mapper:  (f, suggestedPath)=>(f.name.endsWith(".txt") && suggestedPath) `

supplied to `zipBucket()`

would work.  This is untested.  

Presumably you know (a,b)=>(expression) is new syntax of anonymous function.
The expression above will be `false` whenever `f.name` does not end with ".txt".  
When `f.name` ends with ".txt" the first part of `&&` will be `true` and the second part will
return string `suggestedPath` from 2nd parameter supplied to `mapper`.  

Because of time zone, you may find quicker answer by asking additional questions on http://stackoverflow.com

-----------------------------------------------------------------------

It seems from Google documentation that the pathDelimiter will **not** perform the task of limiting file list to particular extension.


delimiter in Google Cloud Storage API has an odd definition.  From https://cloud.google.com/nodejs/docs/reference/storage/1.3.x/global#GetFilesRequest

it says that it will **exclude** files that contain the delimiter.

> delimiter
> 
> Optional
> 
> string
> 
> Results will contain only objects whose names, aside from the prefix, do not contain delimiter. Objects whose names, aside from the prefix, contain delimiter will have their name truncated after the delimiter, returned in apiResponse.prefixes. Duplicate prefixes are omitted.
